### ISSUE TITLE
Allow users to change the card status for the entered card number using Mobile app.

### ISSUE THREAD

**Issue by pwaste** [akhada/baWall#3]

**Comment by anaynayak** [comment]
@piyush-nimbalkar has provided the server side api to transition a card based on the current state of the issue. It works well for really simple scenarios but we still need to handle various edge cases.

**Comment by priyaaank** [comment]
It is a relief that this issue got closed. I was losing sleep for last 4 years about whether someone will ever fix it or not!

**Comment by piyush-nimbalkar** [comment]
😆

**Comment by ketansoni** [comment]
I know...Did PO accept it?

**Comment by priyaaank** [comment]
Well it is atleast working on my machine

**Comment by anaynayak** [comment]
Damn! If only we had incorporated ads we would have made millions by now!

**Comment by ketansoni** [comment]
Priyank! Where is my share of million dollars??

**Comment by priyaaank** [comment]
Where is the million dollar idea. I hope that group still exists

**Comment by pwaste** [comment]
I was trying to use huboard for this card.



[image: http://]

Prasanna Vaste
[image: http://]about.me/prasannavaste
<http://about.me/prasannavaste>
